spring:
  application:
    name: micro-ms-reports
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      import-check:
        enabled: true
      enabled: true
      label: main